import Head from 'next/head'
import styles from '../styles/Landing.module.css'
import Footer from '../src/component/footer/footer'
import React, { Component } from 'react';
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from 'react-responsive-carousel';
import Image from 'next/image';
import Link from 'next/link';
import { Button } from 'react-bootstrap';




export default function Landing() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing Page | Wakanda</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className={styles.main}>
        <div className={styles.content}>
          <div> 
              <h1 className={styles.tittle}>PLAY TRADITIONAL GAME</h1>
              <h4 className={styles.subtittle}>Press login to play games with us now!!!</h4>
              <Link href='./auth/login' passHref>
                <Button variant="contained" className={styles.buttonLogin} >Login</Button>
              </Link>
          </div>
          <div className={styles.carousel}>
            <Carousel showThumbs={false}>
              <div>
                <Image src="/assets/village.png" width={300} height={500} alt='game 1' />
                <p className="legend">Villagers Power</p>
              </div>
              <div>
                <Image src="/assets/2048.png" width={300} height={500} alt=' game 2' />
                <p className="legend">2048</p>
              </div>
              <div>
                <Image src="/assets/rock-paper.png" width={300} height={500} alt='game 3' />
                <p className="legend">Rock Paper Scissors</p>
              </div>
            </Carousel>
          </div>
        </div>
        <div className={styles.footer}>
          <Footer />
        </div>
      </div>
    </div>
  )
}
